import { SkillType } from '../types/skills';
import type { ClassSpecificSkills } from '../types/skills';
import { StatusEffectType } from '../types/status';
import { BaseClass } from '../types/jobs';

export const CLASS_SPECIFIC_SKILLS: Record<number, ClassSpecificSkills> = {
  0: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
  },
  1: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Empower (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase attack power of melee weapons",
      skillType: SkillType.PASSIVE,
    },
    "Leg Sweep": {
      reqLevel: 20,
      mpCost: 21,
      castTime: 0,
      cooldown: 10,
      duration: 5,
      description: "Attack and reduce target's movement speed",
      skillType: SkillType.DAMAGE_PHYSICAL,
      onHitEffects: [{ type: StatusEffectType.SLOW, duration: 5 }],
    },
    "War Cry": {
      reqLevel: 28,
      mpCost: 35,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase attack power of all allies",
      isAOE: true,
      aoeRadius: 15,
      buffEffectTable: {
        attackPowerMultiplier: 1.4,
      },
      skillType: SkillType.BUFF,
    },
    "Raging Soul": {
      reqLevel: 35,
      mpCost: 35,
      castTime: 0,
      cooldown: 60,
      duration: 30,
      description: "Increase attack power of next attack",
      skillType: SkillType.BUFF,
    },
  },
  2: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Empower (Passive)": {
      reqLevel: 18,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase attack power of melee weapons",
      skillType: SkillType.PASSIVE,
    },
    "Leg Sweep": {
      reqLevel: 20,
      mpCost: 21,
      castTime: 0,
      cooldown: 10,
      duration: 5,
      description: "Attack and reduce target's movement speed",
      skillType: SkillType.DAMAGE_PHYSICAL,
      onHitEffects: [{ type: StatusEffectType.SLOW, duration: 5 }],
    },
    "War Cry": {
      reqLevel: 28,
      mpCost: 35,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase attack power of all allies",
      skillType: SkillType.BUFF,
    },
    "Raging Soul": {
      reqLevel: 35,
      mpCost: 35,
      castTime: 0,
      cooldown: 60,
      duration: 30,
      description: "Increase attack power of next attack",
      skillType: SkillType.BUFF,
    },
    "Desperado": {
      reqLevel: 45,
      mpCost: 39,
      castTime: 0,
      cooldown: 35,
      duration: 60,
      description: "Attack Power increased, damage taken increased",
      skillType: SkillType.BUFF,
    },
    "Skill Focus": {
      reqLevel: 50,
      mpCost: 3,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Sacrifice 30% of your current HP to cut CDs by 50%",
      skillType: SkillType.UTILITY,
    },
  },
  3: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Empower (Passive)": {
      reqLevel: 18,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase attack power of melee weapons",
      skillType: SkillType.PASSIVE,
    },
    "Leg Sweep": {
      reqLevel: 20,
      mpCost: 21,
      castTime: 0,
      cooldown: 10,
      duration: 5,
      description: "Attack and reduce target's movement speed",
      skillType: SkillType.DAMAGE_PHYSICAL,
      onHitEffects: [{ type: StatusEffectType.SLOW, duration: 5 }],
    },
    "War Cry": {
      reqLevel: 28,
      mpCost: 35,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase attack power of all allies",
      skillType: SkillType.BUFF,
    },
    "Raging Soul": {
      reqLevel: 35,
      mpCost: 35,
      castTime: 0,
      cooldown: 60,
      duration: 30,
      description: "Increase attack power of next attack",
      skillType: SkillType.BUFF,
    },
    "Equine Charge": {
      reqLevel: 45,
      mpCost: 19,
      castTime: 0,
      cooldown: 9,
      duration: 0,
      description: "Charge at target with your spear",
      skillType: SkillType.DAMAGE_PHYSICAL,
    },
    "Jousting (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can use skills and charge on horseback",
      skillType: SkillType.PASSIVE,
    },
    "Charge": {
      reqLevel: 50,
      mpCost: 41,
      castTime: 0,
      cooldown: 20,
      duration: 0,
      description: "Mounted Charge/Dash/Rush (Spear)",
      skillType: SkillType.DAMAGE_PHYSICAL,
    },
  },
  4: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Obscene Gesture": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 10,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Providence": {
      reqLevel: 28,
      mpCost: 62,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "+25 magic resistance for yourself and party",
      skillType: SkillType.BUFF,
    },
  },
  5: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Obscene Gesture": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 10,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Providence": {
      reqLevel: 28,
      mpCost: 62,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "+25 magic resistance for yourself and party",
      skillType: SkillType.BUFF,
    },
    "Deflect (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Automatically deflects charge damage when blocking (Shield)",
      skillType: SkillType.PASSIVE,
    },
    "Jousting (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can use skills and charge on horseback",
      skillType: SkillType.PASSIVE,
    },
    "Bore Brunt": {
      reqLevel: 50,
      reqPoints: [{ skillName: "Defend", points: 54 }],
      mpCost: 16,
      castTime: 4,
      cooldown: 1,
      duration: 300,
      description: "Take damage for up to three party members",
      skillType: SkillType.UTILITY,
    },
  },
  6: {
    "Provoke": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 1,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Brewer (Passive)": {
      reqLevel: 12,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "12% more potion effectiveness",
      skillType: SkillType.PASSIVE,
    },
    "Lunge": {
      reqLevel: 15,
      mpCost: 25,
      castTime: 0,
      cooldown: 30,
      duration: 120,
      description: "Increased attack speed with melee weapons",
      skillType: SkillType.BUFF,
    },
    "Obscene Gesture": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 15,
      duration: 10,
      description: "Provoke target to attack you",
      skillType: SkillType.DEBUFF,
    },
    "Providence": {
      reqLevel: 28,
      mpCost: 62,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "+25 magic resistance for yourself and party",
      skillType: SkillType.BUFF,
    },
    "Strong Stance (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can use shield to block magic",
      skillType: SkillType.PASSIVE,
    },
    "Jousting (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can use skills and charge on horseback",
      skillType: SkillType.PASSIVE,
    },
    "Defensive Attack (Passive)": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can use offensive skills while blocking",
      skillType: SkillType.PASSIVE,
    },
  },
  7: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
  },
  8: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Hawkeye (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase accuracy",
      skillType: SkillType.PASSIVE,
    },
    "Accelerate": {
      reqLevel: 28,
      mpCost: 16,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase movement speed of target",
      skillType: SkillType.BUFF,
    },
    "Rapid Fire": {
      reqLevel: 35,
      mpCost: 45,
      castTime: 0,
      cooldown: 45,
      duration: 0,
      description: "Increase attack speed (crossbow)",
      skillType: SkillType.BUFF,
    },
  },
  9: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Hawkeye (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase accuracy",
      skillType: SkillType.PASSIVE,
    },
    "Accelerate": {
      reqLevel: 28,
      mpCost: 16,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase movement speed of target",
      skillType: SkillType.BUFF,
    },
    "Rapid Fire": {
      reqLevel: 35,
      mpCost: 45,
      castTime: 0,
      cooldown: 45,
      duration: 0,
      description: "Increase attack speed (crossbow)",
      skillType: SkillType.BUFF,
    },
    "Snipers Nest": {
      reqLevel: 45,
      mpCost: 45,
      castTime: 2,
      cooldown: 5,
      duration: 0,
      description: "Attack Power, Accuracy, Range buff while stationary (Bow, Crossbow)",
      skillType: SkillType.BUFF,
    },
    "Kindling Arrow": {
      reqLevel: 50,
      mpCost: 41,
      castTime: 1,
      cooldown: 15,
      duration: 0,
      description: "AOE fire field (bow)",
      skillType: SkillType.FIELD_SPELL,
    },
  },
  10: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Hawkeye (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase accuracy",
      skillType: SkillType.PASSIVE,
    },
    "Accelerate": {
      reqLevel: 28,
      mpCost: 16,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Increase movement speed of target",
      skillType: SkillType.BUFF,
    },
    "Rapid Fire": {
      reqLevel: 35,
      mpCost: 45,
      castTime: 0,
      cooldown: 45,
      duration: 0,
      description: "Increase attack speed (crossbow)",
      skillType: SkillType.BUFF,
    },
    "Watchful Eye": {
      reqLevel: 45,
      mpCost: 44,
      castTime: 2,
      cooldown: 20,
      duration: 0,
      description: "Become stationary to see and attack invisible targets",
      skillType: SkillType.UTILITY,
    },
    "Horse Archer": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 90,
      duration: 0,
      description: "Allows you to use certain skills while mounted",
      skillType: SkillType.UTILITY,
    },
    "Arrow Fusillade (Passive)": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "+2 range and double attack with crossbow",
      skillType: SkillType.PASSIVE,
    },
  },
  11: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Shifty (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Dodge rate buff",
      skillType: SkillType.PASSIVE,
    },
    "Cloak": {
      reqLevel: 20,
      mpCost: 45,
      castTime: 2,
      cooldown: 20,
      duration: 0,
      description: "Mobile invisibility (3MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Third Eye": {
      reqLevel: 28,
      mpCost: 48,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Accuracy buff",
      skillType: SkillType.BUFF,
    },
  },
  12: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Shifty (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Dodge rate buff",
      skillType: SkillType.PASSIVE,
    },
    "Cloak": {
      reqLevel: 20,
      mpCost: 45,
      castTime: 2,
      cooldown: 20,
      duration: 0,
      description: "Mobile invisibility (3MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Third Eye": {
      reqLevel: 28,
      mpCost: 48,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Accuracy buff",
      skillType: SkillType.BUFF,
    },
    "Furtive Steps (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "No cloaked movement penalty, minor MP regen buff",
      skillType: SkillType.PASSIVE,
    },
    "Counterpunch": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 90,
      duration: 0,
      description: "Weak counter attack with knuckles",
      skillType: SkillType.DAMAGE_PHYSICAL,
    },
  },
  13: {
    "Invigorate": {
      reqLevel: 5,
      mpCost: 16,
      castTime: 0,
      cooldown: 10,
      duration: 180,
      description: "Increase movement speed",
      skillType: SkillType.BUFF,
    },
    "Hide": {
      reqLevel: 18,
      mpCost: 24,
      castTime: 0,
      cooldown: 3,
      duration: 0,
      description: "Stationary invisibility (2MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Shifty (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Dodge rate buff",
      skillType: SkillType.PASSIVE,
    },
    "Cloak": {
      reqLevel: 20,
      mpCost: 45,
      castTime: 2,
      cooldown: 20,
      duration: 0,
      description: "Mobile invisibility (3MP per second)",
      skillType: SkillType.UTILITY,
    },
    "Third Eye": {
      reqLevel: 28,
      mpCost: 48,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Accuracy buff",
      skillType: SkillType.BUFF,
    },
    "Treachery (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Can remain cloaked while placing traps",
      skillType: SkillType.PASSIVE,
    },
  },
  14: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
  },
  15: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Inspiration (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase SPI based on Prayer proficiency",
      skillType: SkillType.PASSIVE,
    },
    "Tranquil Mind": {
      reqLevel: 20,
      mpCost: 50,
      castTime: 5,
      cooldown: 20,
      duration: 120,
      description: "Increase MP regen for party",
      skillType: SkillType.BUFF,
    },
    "Divine Aid": {
      reqLevel: 28,
      mpCost: 89,
      castTime: 4,
      cooldown: 1.54,
      duration: 480,
      description: "Increase LP for party, 15% of base LP + 250",
      skillType: SkillType.HP_BUFF,
    },
    "Revive": {
      reqLevel: 35,
      mpCost: 65,
      castTime: 5,
      cooldown: 30,
      duration: 0,
      description: "Revive a fallen ally, restoring them with partial HP. Consumes 3 Holy Water.",
      skillType: SkillType.REVIVE,
      consumableItem: 'Holy Water',
      consumableItemQuantity: 3,
    },
  },
  16: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Inspiration (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase SPI based on Prayer proficiency",
      skillType: SkillType.PASSIVE,
    },
    "Tranquil Mind": {
      reqLevel: 20,
      mpCost: 50,
      castTime: 5,
      cooldown: 20,
      duration: 120,
      description: "Increase MP regen for party",
      skillType: SkillType.BUFF,
    },
    "Divine Aid": {
      reqLevel: 28,
      mpCost: 89,
      castTime: 4,
      cooldown: 1.54,
      duration: 480,
      description: "Increase LP for party, 15% of base LP + 250",
      skillType: SkillType.HP_BUFF,
    },
    "Revive": {
      reqLevel: 35,
      mpCost: 65,
      castTime: 5,
      cooldown: 30,
      duration: 0,
      description: "Revive a fallen ally, restoring them with partial HP. Consumes 3 Holy Water.",
      skillType: SkillType.REVIVE,
      consumableItem: 'Holy Water',
      consumableItemQuantity: 3,
    },
    "Sanctuary": {
      reqLevel: 45,
      mpCost: 87,
      castTime: 5,
      cooldown: 60,
      duration: 0,
      description: "AOE LP regen",
      skillType: SkillType.PARTY_HEAL,
      healing: { type: 'party' },
    },
    "Merciful Blessing (Passive)": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase strength of heals, First Aid is instant cast",
      skillType: SkillType.PASSIVE,
    },
  },
  17: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Inspiration (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase SPI based on Prayer proficiency",
      skillType: SkillType.PASSIVE,
    },
    "Tranquil Mind": {
      reqLevel: 20,
      mpCost: 50,
      castTime: 5,
      cooldown: 20,
      duration: 120,
      description: "Increase MP regen for party",
      skillType: SkillType.BUFF,
    },
    "Revive": {
      reqLevel: 35,
      mpCost: 65,
      castTime: 5,
      cooldown: 30,
      duration: 0,
      description: "Revive a fallen ally, restoring them with partial HP. Consumes 3 Holy Water.",
      skillType: SkillType.REVIVE,
      consumableItem: 'Holy Water',
      consumableItemQuantity: 3,
    },
    "Enchantment": {
      reqLevel: 45,
      mpCost: 68,
      castTime: 0.5,
      cooldown: 1.5,
      duration: 480,
      description: "Aura power buff and magical attack power buff",
      skillType: SkillType.BUFF,
    },
    "Karmic Aura (Passive)": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Toggle to enable AOE buffs",
      skillType: SkillType.PASSIVE,
    },
  },
  18: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Blessed Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Poison, Charm, and Magic resistance increase when gear is enhanced with holy",
      skillType: SkillType.PASSIVE,
    },
    "Mana Restore": {
      reqLevel: 20,
      mpCost: 32,
      castTime: 1.5,
      cooldown: 10,
      duration: 210,
      description: "Restore MP over time",
      skillType: SkillType.MP_RESTORE,
    },
    "Speedy Gale": {
      reqLevel: 28,
      mpCost: 55,
      castTime: 0,
      cooldown: 1,
      duration: 480,
      description: "Increase dodge rate",
      isAOE: true,
      buffEffectTable: {
        spiValues: [
          {
            value: 33,
            Blessing: [
              { value: 8, dodgeChance: 13 },
              { value: 16, dodgeChance: 18 },
              { value: 24, dodgeChance: 24 },
              { value: 31, dodgeChance: 30 },
              { value: 39, dodgeChance: 37 },
              { value: 47, dodgeChance: 43 },
            ],
          },
          {
            value: 50,
            Blessing: [
              { value: 8, dodgeChance: 16 },
              { value: 16, dodgeChance: 22 },
              { value: 24, dodgeChance: 28 },
              { value: 31, dodgeChance: 35 },
              { value: 39, dodgeChance: 41 },
              { value: 47, dodgeChance: 48 },
            ],
          },
          {
            value: 67,
            Blessing: [
              { value: 8, dodgeChance: 20 },
              { value: 16, dodgeChance: 26 },
              { value: 24, dodgeChance: 33 },
              { value: 31, dodgeChance: 40 },
              { value: 39, dodgeChance: 46 },
              { value: 47, dodgeChance: 53 },
            ],
          },
          {
            value: 100,
            Blessing: [
              { value: 8, dodgeChance: 24 },
              { value: 16, dodgeChance: 30 },
              { value: 24, dodgeChance: 37 },
              { value: 31, dodgeChance: 44 },
              { value: 39, dodgeChance: 51 },
              { value: 47, dodgeChance: 58 },
            ],
          },
        ],
      },
      skillType: SkillType.BUFF,
    },
  },
  19: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Blessed Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Poison, Charm, and Magic resistance increase when gear is enhanced with holy",
      skillType: SkillType.PASSIVE,
    },
    "Mana Restore": {
      reqLevel: 20,
      mpCost: 32,
      castTime: 1.5,
      cooldown: 10,
      duration: 210,
      description: "Restore MP over time",
      skillType: SkillType.MP_RESTORE,
    },
    "Speedy Gale": {
      reqLevel: 28,
      mpCost: 55,
      castTime: 0,
      cooldown: 1,
      duration: 480,
      description: "Increase dodge rate",
      isAOE: true,
      buffEffectTable: {
        spiValues: [
          {
            value: 33,
            Blessing: [
              { value: 8, dodgeChance: 13 },
              { value: 16, dodgeChance: 18 },
              { value: 24, dodgeChance: 24 },
              { value: 31, dodgeChance: 30 },
              { value: 39, dodgeChance: 37 },
              { value: 47, dodgeChance: 43 },
            ],
          },
          {
            value: 50,
            Blessing: [
              { value: 8, dodgeChance: 16 },
              { value: 16, dodgeChance: 22 },
              { value: 24, dodgeChance: 28 },
              { value: 31, dodgeChance: 35 },
              { value: 39, dodgeChance: 41 },
              { value: 47, dodgeChance: 48 },
            ],
          },
          {
            value: 67,
            Blessing: [
              { value: 8, dodgeChance: 20 },
              { value: 16, dodgeChance: 26 },
              { value: 24, dodgeChance: 33 },
              { value: 31, dodgeChance: 40 },
              { value: 39, dodgeChance: 46 },
              { value: 47, dodgeChance: 53 },
            ],
          },
          {
            value: 100,
            Blessing: [
              { value: 8, dodgeChance: 24 },
              { value: 16, dodgeChance: 30 },
              { value: 24, dodgeChance: 37 },
              { value: 31, dodgeChance: 44 },
              { value: 39, dodgeChance: 51 },
              { value: 47, dodgeChance: 58 },
            ],
          },
        ],
      },
      skillType: SkillType.BUFF,
    },
    "Sound Mind (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Reduce duration of magic debuffs",
      skillType: SkillType.PASSIVE,
    },
    "Paralyzing Bond": {
      reqLevel: 50,
      mpCost: 47,
      castTime: 0,
      cooldown: 30,
      duration: 10,
      description: "Root target in place. Both you and target are immobile",
      skillType: SkillType.DEBUFF,
      onHitEffects: [{ type: StatusEffectType.ROOT, duration: 10 }],
    },
  },
  20: {
    "Meditation (Passive)": {
      reqLevel: 5,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase MP regen",
      skillType: SkillType.PASSIVE,
    },
    "Heal": {
      reqLevel: 18,
      mpCost: 62,
      castTime: 2,
      cooldown: 3,
      duration: 0,
      description: "Heal target",
      skillType: SkillType.HEAL,
      healing: { type: 'single' },
    },
    "Blessed Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Poison, Charm, and Magic resistance increase when gear is enhanced with holy",
      skillType: SkillType.PASSIVE,
    },
    "Mana Restore": {
      reqLevel: 20,
      mpCost: 32,
      castTime: 1.5,
      cooldown: 10,
      duration: 210,
      description: "Restore MP over time",
      skillType: SkillType.MP_RESTORE,
    },
    "Speedy Gale": {
      reqLevel: 28,
      mpCost: 55,
      castTime: 0,
      cooldown: 1,
      duration: 480,
      description: "Increase dodge rate",
      isAOE: true,
      buffEffectTable: {
        spiValues: [
          {
            value: 33,
            Blessing: [
              { value: 8, dodgeChance: 13 },
              { value: 16, dodgeChance: 18 },
              { value: 24, dodgeChance: 24 },
              { value: 31, dodgeChance: 30 },
              { value: 39, dodgeChance: 37 },
              { value: 47, dodgeChance: 43 },
            ],
          },
          {
            value: 50,
            Blessing: [
              { value: 8, dodgeChance: 16 },
              { value: 16, dodgeChance: 22 },
              { value: 24, dodgeChance: 28 },
              { value: 31, dodgeChance: 35 },
              { value: 39, dodgeChance: 41 },
              { value: 47, dodgeChance: 48 },
            ],
          },
          {
            value: 67,
            Blessing: [
              { value: 8, dodgeChance: 20 },
              { value: 16, dodgeChance: 26 },
              { value: 24, dodgeChance: 33 },
              { value: 31, dodgeChance: 40 },
              { value: 39, dodgeChance: 46 },
              { value: 47, dodgeChance: 53 },
            ],
          },
          {
            value: 100,
            Blessing: [
              { value: 8, dodgeChance: 24 },
              { value: 16, dodgeChance: 30 },
              { value: 24, dodgeChance: 37 },
              { value: 31, dodgeChance: 44 },
              { value: 39, dodgeChance: 51 },
              { value: 47, dodgeChance: 58 },
            ],
          },
        ],
      },
      skillType: SkillType.BUFF,
    },
    "Mana Swap": {
      reqLevel: 45,
      mpCost: 16,
      castTime: 2,
      cooldown: 10,
      duration: 0,
      description: "Swap MP with target",
      skillType: SkillType.UTILITY,
    },
    "Soul Swap": {
      reqLevel: 50,
      mpCost: 21,
      castTime: 1,
      cooldown: 10,
      duration: 0,
      description: "Swap buffs with target",
      skillType: SkillType.UTILITY,
    },
  },
  21: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
  },
  22: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Scholar (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Elemental proficiency increases elemental damage",
      skillType: SkillType.PASSIVE,
    },
    "Thunder Crash": {
      reqLevel: 20,
      mpCost: 78,
      castTime: 3.5,
      cooldown: 12,
      duration: 0,
      description: "Strike the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
  },
  23: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Scholar (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Elemental proficiency increases elemental damage",
      skillType: SkillType.PASSIVE,
    },
    "Thunder Crash": {
      reqLevel: 20,
      mpCost: 78,
      castTime: 3.5,
      cooldown: 12,
      duration: 0,
      description: "Strike the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Magical Aid": {
      reqLevel: 45,
      mpCost: 56,
      castTime: 2.5,
      cooldown: 15,
      duration: 0,
      description: "Increase strength of next magical attack",
      skillType: SkillType.BUFF,
    },
  },
  24: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Scholar (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Elemental proficiency increases elemental damage",
      skillType: SkillType.PASSIVE,
    },
    "Thunder Crash": {
      reqLevel: 20,
      mpCost: 78,
      castTime: 3.5,
      cooldown: 12,
      duration: 0,
      description: "Strike the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Teleport": {
      reqLevel: 45,
      mpCost: 24,
      castTime: 2,
      cooldown: 300,
      duration: 0,
      description: "Create a portal to a memorized a location outside of town",
      skillType: SkillType.UTILITY,
    },
    "Memorize": {
      reqLevel: 45,
      mpCost: 10,
      castTime: 1,
      cooldown: 5,
      duration: 0,
      description: "Memorize a location outside of town",
      skillType: SkillType.UTILITY,
    },
    "Intelleto": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase number of locations that can be memorized",
      skillType: SkillType.UTILITY,
    },
    "Supreme Mind (Passive)": {
      reqLevel: 50,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increases power and reduces cooldown of invocation spells, soul bright is a 5s debuff",
      skillType: SkillType.PASSIVE,
    },
  },
  25: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Shadow Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Fire, Ice, and Lightning resistance increase when gear is enhanced with dark",
      skillType: SkillType.PASSIVE,
    },
  },
  26: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Shadow Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Fire, Ice, and Lightning resistance increase when gear is enhanced with dark",
      skillType: SkillType.PASSIVE,
    },
    "Discomfort (Passive)": {
      reqLevel: 60,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Increase debuff duration +5%",
      skillType: SkillType.PASSIVE,
    },
  },
  27: {
    "Fire Bolt": {
      reqLevel: 1,
      mpCost: 28,
      castTime: 0.8,
      cooldown: 2,
      duration: 0,
      description: "Fire a bolt of fire at target",
      skillType: SkillType.DAMAGE_MAGICAL,
    },
    "Shock": {
      reqLevel: 12,
      mpCost: 44,
      castTime: 0.5,
      cooldown: 20,
      duration: 0,
      description: "Trip the target with electricity",
      skillType: SkillType.DAMAGE_MAGICAL,
      onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
    },
    "Shadow Garments (Passive)": {
      reqLevel: 20,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Fire, Ice, and Lightning resistance increase when gear is enhanced with dark",
      skillType: SkillType.PASSIVE,
    },
    "Dark Shield (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Reduce recoil damage from Gloom",
      skillType: SkillType.PASSIVE,
    },
    "Median Riding (Passive)": {
      reqLevel: 45,
      mpCost: 0,
      castTime: 0,
      cooldown: 0,
      duration: 0,
      description: "Gain ability to cast spells while mounted",
      skillType: SkillType.PASSIVE,
    },
  },
};

const BASE_CLASS_OFFSETS: Record<string, number> = {
  [BaseClass.WARRIOR]: 0,
  [BaseClass.SCOUT]: 7,
  [BaseClass.ACOLYTE]: 14,
  [BaseClass.MAGE]: 21,
};

export const JOB_TO_CLASS_SKILLS_INDEX: Record<string, number> = {
  'warrior': 0,
  'gladiator': 1,
  'juggernaut': 2,
  'dragoon': 3,
  'knight': 4,
  'warlord': 4,
  'paladin': 5,
  'scout': 7,
  'archer': 8,
  'sniper': 9,
  'hunter': 8,
  'provocateur': 11,
  'assassin': 13,
  'saboteur': 11,
  'shadowblade': 12,
  'acolyte': 14,
  'priest': 15,
  'cleric': 16,
  'enchanter': 17,
  'ascetic': 18,
  'monk': 19,
  'exorcist': 19,
  'mage': 21,
  'wizard': 22,
  'warlock': 23,
  'conjurer': 24,
  'sorcerer': 25,
  'corruptor': 26,
};

export function getClassSpecificSkillsForJob(jobId: string, baseClass: BaseClass): ClassSpecificSkills {
  const index = JOB_TO_CLASS_SKILLS_INDEX[jobId];
  if (index !== undefined && CLASS_SPECIFIC_SKILLS[index]) {
    return CLASS_SPECIFIC_SKILLS[index];
  }
  const offset = BASE_CLASS_OFFSETS[baseClass];
  if (offset !== undefined && CLASS_SPECIFIC_SKILLS[offset]) {
    return CLASS_SPECIFIC_SKILLS[offset];
  }
  return {};
}
