export const GAME_CONFIG = {
  TICK_RATE: 30,
  PLAYER_SPEED: 5,
  PLAYER_ROTATION_SPEED: 3,
  JUMP_FORCE: 8,
  GRAVITY: 20,
  MAX_HEALTH: 100,
  RESPAWN_TIME: 5000,
  ZONE_SIZE: 100,
  VIEW_DISTANCE: 50,
  INTERPOLATION_DELAY: 100
} as const;

export const COMBAT_CONFIG = {
  BASE_ATTACK_POWER: 10,
  BASE_DEFENSE: 5,
  BASE_ATTACK_SPEED: 1.0,
  CRITICAL_CHANCE: 0.1,
  CRITICAL_MULTIPLIER: 2.0
} as const;

export const NETWORK_CONFIG = {
  HEARTBEAT_INTERVAL: 30000,
  CONNECTION_TIMEOUT: 10000,
  MAX_RECONNECT_ATTEMPTS: 5,
  RECONNECT_DELAY: 2000
} as const;

export const WORLD_CONFIG = {
  CHUNK_SIZE: 32,
  MAX_ENTITIES_PER_ZONE: 100,
  SPAWN_RADIUS: 10,
  DESPAWN_DISTANCE: 100
} as const;