import { ItemDefinition, ItemType, ItemRarity, EquipmentSlot } from '../types/items';

export const ITEM_DATABASE: Record<string, ItemDefinition> = {
  'wooden_sword': {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { attack: 5 },
    description: 'A basic training sword.',
    maxStack: 1,
    sellPrice: 5,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'iron_sword': {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: ItemType.WEAPON,
    rarity: ItemRarity.UNCOMMON,
    stats: { attack: 12, criticalChance: 0.05, accuracy: 3 },
    description: 'A sturdy iron blade. +3 Accuracy.',
    maxStack: 1,
    sellPrice: 25,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'steel_blade': {
    id: 'steel_blade',
    name: 'Steel Blade',
    type: ItemType.WEAPON,
    rarity: ItemRarity.RARE,
    stats: { attack: 22, criticalChance: 0.1, accuracy: 7, attackSpeed: 0.05 },
    description: 'A finely crafted steel sword. +7 Accuracy, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 80,
    requiredLevel: 10,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'leather_armor': {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: ItemType.ARMOR,
    rarity: ItemRarity.COMMON,
    stats: { defense: 5, health: 10 },
    description: 'Basic leather protection.',
    maxStack: 1,
    sellPrice: 8,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'chainmail': {
    id: 'chainmail',
    name: 'Chainmail',
    type: ItemType.ARMOR,
    rarity: ItemRarity.UNCOMMON,
    stats: { defense: 12, health: 25, dodge: 2 },
    description: 'Interlocking metal rings provide good protection. +2 Dodge.',
    maxStack: 1,
    sellPrice: 35,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'plate_armor': {
    id: 'plate_armor',
    name: 'Plate Armor',
    type: ItemType.ARMOR,
    rarity: ItemRarity.RARE,
    stats: { defense: 22, health: 50, dodge: -2, fireResist: 5, iceResist: 5 },
    description: 'Heavy plate armor for maximum protection. +5 Fire/Ice Resist, -2 Dodge.',
    maxStack: 1,
    sellPrice: 100,
    requiredLevel: 10,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'cloth_helmet': {
    id: 'cloth_helmet',
    name: 'Cloth Hood',
    type: ItemType.HELMET,
    rarity: ItemRarity.COMMON,
    stats: { defense: 2, mana: 10 },
    description: 'A simple cloth hood.',
    maxStack: 1,
    sellPrice: 4,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.HELMET
  },
  'iron_helmet': {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    type: ItemType.HELMET,
    rarity: ItemRarity.UNCOMMON,
    stats: { defense: 8, lightningResist: 5 },
    description: 'A solid iron helmet. +5 Lightning Resist.',
    maxStack: 1,
    sellPrice: 20,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.HELMET
  },
  'leather_boots': {
    id: 'leather_boots',
    name: 'Leather Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.COMMON,
    stats: { defense: 3, speed: 0.05 },
    description: 'Comfortable leather boots. +5% Movement Speed.',
    maxStack: 1,
    sellPrice: 5,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'swift_boots': {
    id: 'swift_boots',
    name: 'Swift Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.RARE,
    stats: { defense: 5, speed: 0.10, dodge: 5, attackSpeed: 0.05 },
    description: 'Enchanted boots that increase movement speed. +10% Movement Speed, +5 Dodge, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 60,
    requiredLevel: 8,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'copper_ring': {
    id: 'copper_ring',
    name: 'Copper Ring',
    type: ItemType.ACCESSORY,
    rarity: ItemRarity.COMMON,
    stats: { health: 5, mana: 5 },
    description: 'A simple copper ring.',
    maxStack: 1,
    sellPrice: 10,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.ACCESSORY
  },
  'flame_amulet': {
    id: 'flame_amulet',
    name: 'Flame Amulet',
    type: ItemType.ACCESSORY,
    rarity: ItemRarity.RARE,
    stats: { INT: 3, fireResist: 15 },
    description: 'An amulet imbued with fire energy. +15 Fire Resist, +3 INT.',
    maxStack: 1,
    sellPrice: 75,
    requiredLevel: 8,
    equipmentSlot: EquipmentSlot.ACCESSORY
  },
  'shadow_cloak': {
    id: 'shadow_cloak',
    name: 'Shadow Cloak',
    type: ItemType.ARMOR,
    rarity: ItemRarity.EPIC,
    stats: { defense: 15, dodge: 8, darkResist: 20, DEX: 4 },
    description: 'A cloak woven from shadow threads. +8 Dodge, +20 Dark Resist, +4 DEX.',
    maxStack: 1,
    sellPrice: 200,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'frost_blade': {
    id: 'frost_blade',
    name: 'Frost Blade',
    type: ItemType.WEAPON,
    rarity: ItemRarity.EPIC,
    stats: { attack: 30, criticalChance: 0.12, accuracy: 10, iceResist: 10, attackSpeed: 0.08 },
    description: 'A blade chilled by eternal frost. +10 Accuracy, +10 Ice Resist, +8% Atk Speed.',
    maxStack: 1,
    sellPrice: 250,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'basic_staff': {
    id: 'basic_staff',
    name: 'Basic Staff',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { magicAttack: 0.05, INT: 6, DEX: 3, SPI: 4 },
    description: 'A basic staff. +5% MATK.',
    maxStack: 1,
    sellPrice: 250,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'thunder_helm': {
    id: 'thunder_helm',
    name: 'Thunder Helm',
    type: ItemType.HELMET,
    rarity: ItemRarity.EPIC,
    stats: { defense: 14, STA: 3, lightningResist: 20, poisonResist: 10 },
    description: 'A helm crackling with static energy. +20 Lightning Resist, +10 Poison Resist, +3 STA.',
    maxStack: 1,
    sellPrice: 180,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.HELMET
  },
  'plague_walkers': {
    id: 'plague_walkers',
    name: 'Plague Walkers',
    type: ItemType.BOOTS,
    rarity: ItemRarity.EPIC,
    stats: { defense: 10, speed: 0.15, AGI: 3, poisonResist: 20, dodge: 4 },
    description: 'Boots that resist all toxins. +15% Movement Speed, +20 Poison Resist, +4 Dodge, +3 AGI.',
    maxStack: 1,
    sellPrice: 160,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'windstrider_boots': {
    id: 'windstrider_boots',
    name: 'Windstrider Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 12, speed: 0.20, AGI: 5, dodge: 6, attackSpeed: 0.05 },
    description: 'Boots enchanted with wind spirits. +20% Movement Speed, +6 Dodge, +5 AGI, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 400,
    requiredLevel: 20,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'dragonscale_ring': {
    id: 'dragonscale_ring',
    name: 'Dragonscale Ring',
    type: ItemType.ACCESSORY,
    rarity: ItemRarity.LEGENDARY,
    stats: { health: 30, mana: 20, fireResist: 25, iceResist: 25, lightningResist: 25, darkResist: 25, poisonResist: 25 },
    description: 'A ring forged from dragon scales. +25 All Resistances.',
    maxStack: 1,
    sellPrice: 500,
    requiredLevel: 20,
    equipmentSlot: EquipmentSlot.ACCESSORY
  },
  'health_potion': {
    id: 'health_potion',
    name: 'Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    stats: { health: 50 },
    description: 'Restores 50 health points.',
    maxStack: 20,
    sellPrice: 5,
    requiredLevel: 1
  },
  'mana_potion': {
    id: 'mana_potion',
    name: 'Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    stats: { mana: 40 },
    description: 'Restores 40 mana points.',
    maxStack: 20,
    sellPrice: 5,
    requiredLevel: 1
  },
  'wolf_pelt': {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'The pelt of a dire wolf. Can be sold or used in crafting.',
    maxStack: 50,
    sellPrice: 3,
    requiredLevel: 0
  },
  'goblin_ear': {
    id: 'goblin_ear',
    name: 'Goblin Ear',
    type: ItemType.QUEST,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'Proof of defeating a goblin.',
    maxStack: 50,
    sellPrice: 1,
    requiredLevel: 0
  },
  'ancient_scroll': {
    id: 'ancient_scroll',
    name: 'Ancient Scroll',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A mysterious scroll with ancient writings.',
    maxStack: 50,
    sellPrice: 10,
    requiredLevel: 0
  },
  'fire_gem': {
    id: 'fire_gem',
    name: 'Fire Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem radiating intense heat. Used in fire enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'ice_gem': {
    id: 'ice_gem',
    name: 'Ice Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem cold to the touch. Used in ice enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'lightning_gem': {
    id: 'lightning_gem',
    name: 'Lightning Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem crackling with static. Used in lightning enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'holy_gem': {
    id: 'holy_gem',
    name: 'Holy Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem glowing with divine light. Used in holy enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'dark_gem': {
    id: 'dark_gem',
    name: 'Dark Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem swallowed by shadow. Used in dark enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'poison_gem': {
    id: 'poison_gem',
    name: 'Poison Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem seeping venomous mist. Used in poison enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'fire_essence': {
    id: 'fire_essence',
    name: 'Fire Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated flame essence. Catalyst for fire weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'fire_catalyst': {
    id: 'fire_catalyst',
    name: 'Ignition Stone',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A stone that burns eternally. Required for fire weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'ice_essence': {
    id: 'ice_essence',
    name: 'Ice Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated frost essence. Catalyst for ice weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'ice_catalyst': {
    id: 'ice_catalyst',
    name: 'Permafrost Shard',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A shard that never thaws. Required for ice weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'lightning_essence': {
    id: 'lightning_essence',
    name: 'Lightning Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated storm essence. Catalyst for lightning weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'lightning_catalyst': {
    id: 'lightning_catalyst',
    name: 'Storm Core',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A core humming with electricity. Required for lightning weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'holy_essence': {
    id: 'holy_essence',
    name: 'Holy Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated divine essence. Catalyst for holy weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'holy_catalyst': {
    id: 'holy_catalyst',
    name: 'Sacred Relic',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A blessed relic. Required for holy weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'dark_essence': {
    id: 'dark_essence',
    name: 'Dark Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated shadow essence. Catalyst for dark weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'dark_catalyst': {
    id: 'dark_catalyst',
    name: 'Void Fragment',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A fragment of pure darkness. Required for dark weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'poison_essence': {
    id: 'poison_essence',
    name: 'Poison Essence',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'Concentrated venom essence. Catalyst for poison weapon enhancement.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'poison_catalyst': {
    id: 'poison_catalyst',
    name: 'Toxin Crystal',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A crystal oozing deadly toxin. Required for poison weapon enhancement.',
    maxStack: 50,
    sellPrice: 25,
    requiredLevel: 0
  },
  'rod_of_origin': {
    id: 'rod_of_origin',
    name: 'Rod of Origin',
    type: ItemType.WEAPON,
    rarity: ItemRarity.LEGENDARY,
    stats: { magicAttack: 0.15, INT: 10, SPI: 8, DEX: 5, accuracy: 8 },
    description: 'A rod of immense arcane power. +15% MATK, +10 INT, +8 SPI, +5 DEX, +8 Accuracy.',
    maxStack: 1,
    sellPrice: 1000,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.WEAPON
  },
  'eternal_torso': {
    id: 'eternal_torso',
    name: 'Eternal Torso',
    type: ItemType.ARMOR,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 30, magicAttack: 0.05, health: 80, SPI: 5 },
    description: 'Armor forged from eternal flame. +5% MATK, +30 Defense, +80 HP, +5 SPI.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'eternal_legs': {
    id: 'eternal_legs',
    name: 'Eternal Legs',
    type: ItemType.BOOTS,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 20, magicAttack: 0.05, speed: 0.10, health: 50, INT: 4 },
    description: 'Leggings forged from eternal flame. +5% MATK, +10% Speed, +20 Defense, +50 HP, +4 INT.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'earring_of_power': {
    id: 'earring_of_power',
    name: 'Earring of Power',
    type: ItemType.ACCESSORY,
    rarity: ItemRarity.EPIC,
    stats: { magicAttack: 0.03, INT: 3, mana: 30 },
    description: 'A glowing earring that amplifies magic. +3% MATK, +3 INT, +30 MP.',
    maxStack: 1,
    sellPrice: 300,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.ACCESSORY
  }
};

export function getItem(id: string): ItemDefinition | undefined {
  return ITEM_DATABASE[id];
}
