import {
  SkillCategoryData,
  SkillCategoryId,
  SkillDefinition,
  ClassSpecificSkill,
  ClassSpecificSkills,
  AOETargetMode,
  MagicalDamageSubType,
  PhysicalDamageSubType,
  DamageType,
} from '../types/skills';

export const GROUND_TARGETED_AOE_SKILLS = new Set([
  'Firestorm',
  'Ice Storm',
  'Thunderstorm',
  'Meteor Storm',
  'Despair Swamp',
  'Ice Tempest',
  'Wasteland',
]);

export const DEFAULT_AOE_RADIUS = 5;

export const SKILL_CATEGORIES: Record<number, SkillCategoryData> = {
  0: {
    name: "Melee",
    skills: [
      { id: 1, name: "Slash", skills: {} },
      { id: 2, name: "Thrust", skills: {} },
      { id: 3, name: "Cleave", skills: {} },
      { id: 4, name: "Bash", skills: {} },
      { id: 5, name: "Defend", skills: {} },
    ],
  },
  6: {
    name: "Technique",
    skills: [
      { id: 7, name: "Shot", skills: {} },
      { id: 8, name: "Alchemy", skills: {} },
      { id: 9, name: "Assassination", skills: {} },
      { id: 10, name: "Trap", skills: {} },
      { id: 11, name: "Dodge", skills: {} },
    ],
  },
  12: {
    name: "Prayer",
    skills: [
      { id: 13, name: "Grace", skills: {} },
      { id: 14, name: "Blessing", skills: {} },
      { id: 15, name: "Exorcism", skills: {} },
      { id: 16, name: "Hymn", skills: {} },
    ],
  },
  17: {
    name: "Magic",
    skills: [
      { id: 18, name: "Elemental", skills: {} },
      { id: 19, name: "Invocation", skills: {} },
      { id: 20, name: "Darkness", skills: {} },
      { id: 21, name: "Confusion", skills: {} },
    ],
  },
  22: {
    name: "Special",
    skills: [
      { id: 23, name: "Racial", skills: {} },
      { id: 24, name: "Horsemanship", skills: {} },
    ],
  },
};

export const CLASS_SKILL_DATA: Record<number, { skills: SkillCategoryData['skills'] }> = {
  0: {
    skills: [
      {
        id: 1,
        name: "Slash",
        skills: {
          "Slice": {
            name: "Slice",
            reqPoints: 8,
            mpCost: 15,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Double attack (1H weapons)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
            baseHits: 2,
          },
          "Whirling Strike": {
            name: "Whirling Strike",
            reqPoints: 12,
            mpCost: 28,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "360 AOE knockback melee attack (2H swords)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 2,
            isAOE: true,
          },
          "Parry": {
            name: "Parry",
            reqPoints: 21,
            mpCost: 9,
            castTime: 0,
            cooldown: 10,
            duration: 2,
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            description: "Block enemy attacks and stun target if blocked (2H weapons, dagger)",
          },
          "Concentration": {
            name: "Concentration",
            reqPoints: 26,
            mpCost: 18,
            castTime: 0,
            cooldown: 20,
            duration: 120,
            isBuff: true,
            description: "Increased accuracy of next attack",
          },
          "Brutal Strike": {
            name: "Brutal Strike",
            reqPoints: 41,
            mpCost: 14,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "100% chance to ignore armor (melee weapons)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Swing": {
            name: "Swing",
            reqPoints: [
              { skillName: "Slash", points: 60 },
              { skillName: "Dodge", points: 15 },
            ],
            mpCost: 16,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "360 AOE melee attack (no knockback) that grants +100 dodge for a short duration (sword)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
            isAOE: true,
          },
          "Sword Mastery (Passive)": {
            name: "Sword Mastery (Passive)",
            reqPoints: 61,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Increased damage with swords and daggers (sword, dagger)",
            damageSubType: PhysicalDamageSubType.SLASH,
            isPassive: true,
          },
          "Dice": {
            name: "Dice",
            reqPoints: 71,
            mpCost: 15,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Replaces Slice, dealing three swift strikes with a chance to bleed (1H weapons and 2H swords)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
            baseHits: 3,
          },
          "Maximum Shoot": {
            name: "Maximum Shoot",
            reqPoints: 81,
            mpCost: 14,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Replaces Brutal Strike, higher damage with chance to knockdown (melee weapons)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "True Whirling Strike": {
            name: "True Whirling Strike",
            reqPoints: 81,
            mpCost: 28,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Replaces Whirling Strike, higher damage and wider range (2H swords)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 2,
            isAOE: true,
          },
          "Finish Detonate": {
            name: "Finish Detonate",
            reqPoints: 90,
            mpCost: 94,
            castTime: 0,
            cooldown: 180,
            duration: 0,
            description: "Strong single-target attack with a long cooldown and high MP cost",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 4,
          },
        },
      },
      {
        id: 2,
        name: "Thrust",
        skills: {
          "Heave": {
            name: "Heave",
            reqPoints: 8,
            mpCost: 16,
            castTime: 2,
            cooldown: 10,
            duration: 0,
            description: "Pierces through all enemies in front of you",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
            isAOE: true,
          },
          "Triple Stab": {
            name: "Triple Stab",
            reqPoints: 26,
            mpCost: 22,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Triple attack (spear)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
            baseHits: 3,
          },
          "Dismounting Stab": {
            name: "Dismounting Stab",
            reqPoints: 35,
            mpCost: 28,
            castTime: 0,
            cooldown: 90,
            duration: 60,
            description: "Attack with a buff that gives a chance to dismount target",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 2,
          },
          "Spear Volley": {
            name: "Spear Volley",
            reqPoints: 41,
            mpCost: 24,
            castTime: 1,
            cooldown: 30,
            duration: 0,
            description: "Ranged attack with spear",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
          },
          "Quadruple Stab": {
            name: "Quadruple Stab",
            reqPoints: 54,
            mpCost: 43,
            castTime: 0,
            cooldown: 16,
            duration: 0,
            description: "Quadruple attack (spear), bonus damage if comboed with Triple Stab",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 2,
            baseHits: 4,
          },
          "Sonic Sting": {
            name: "Sonic Sting",
            reqPoints: [
              { skillName: "Thrust", points: 60 },
              { skillName: "Ranged", points: 15 },
            ],
            mpCost: 39,
            castTime: 1.5,
            cooldown: 31,
            duration: 0,
            description: "Ranged spear attack",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 2,
          },
          "Neck Press": {
            name: "Neck Press",
            reqPoints: [
              { skillName: "Thrust", points: 60 },
              { skillName: "Defend", points: 15 },
            ],
            mpCost: 39,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Interrupts enemy casting",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
          },
          "Lance Mastery (Passive)": {
            name: "Lance Mastery (Passive)",
            reqPoints: 61,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Increased attack range with spears",
            isPassive: true,
          },
          "Horse Assault": {
            name: "Horse Assault",
            reqPoints: 71,
            mpCost: 13,
            castTime: 0,
            cooldown: 7,
            duration: 0,
            description: "Bonus damage vs mounted enemies and chance to dismount enemies (speaer)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
          },
          "Assault": {
            name: "Assault",
            reqPoints: 81,
            mpCost: 24,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Rush forward and deal multiple hits of damage in a frontal cone AOE",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
            isAOE: true,
          },
          "Godlike": {
            name: "Godlike",
            reqPoints: 90,
            mpCost: 52,
            castTime: 1.5,
            cooldown: 30,
            duration: 0,
            description: "Strong single target attack with knockback",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 3,
          },
        },
      },
      {
        id: 3,
        name: "Cleave",
        skills: {
          "Clobber": {
            name: "Clobber",
            reqPoints: 8,
            mpCost: 19,
            castTime: 0,
            cooldown: 25,
            duration: 0,
            description: "Attack + increased chance of a critical hit (axe, unusable by ascetics)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 1,
          },
          "Riposte": {
            name: "Riposte",
            reqPoints: 12,
            mpCost: 12,
            castTime: 0.5,
            cooldown: 10,
            duration: 2,
            description: "Immobile defensive stance that counter attacks if hit during the duration (2H weapons)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Roar": {
            name: "Roar",
            reqPoints: 21,
            mpCost: 30,
            castTime: 0,
            cooldown: 120,
            duration: 60,
            description: "Increased critical hit rate (axe)",
            isBuff: true,
          },
          "Split": {
            name: "Split",
            reqPoints: 41,
            mpCost: 22,
            castTime: 0,
            cooldown: 20,
            duration: 0,
            description: "Short range frontal AOE attack (axe)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 1,
            isAOE: true,
          },
          "Full Swing": {
            name: "Full Swing",
            reqPoints: [
              { skillName: "Cleave", points: 60 },
              { skillName: "Dodge", points: 15 },
            ],
            mpCost: 16,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "360 AOE melee attack (no knockback) that grants +100 dodge for a short duration (axe)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 1,
            isAOE: true,
          },
          "Axe Mastery (Passive)": {
            name: "Axe Mastery (Passive)",
            reqPoints: 61,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Increased critical damage with axes",
            isPassive: true,
          },
          "Desperate Strike": {
            name: "Desperate Strike",
            reqPoints: 71,
            mpCost: 36,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Attack with a chance to stun target, stuns you on failure",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 2,
          },
          "Grand Quake": {
            name: "Grand Quake",
            reqPoints: [
              { skillName: "Cleave", points: 78 },
              { skillName: "Bash", points: 26 },
            ],
            mpCost: 198,
            castTime: 0,
            cooldown: 40,
            duration: 0,
            description: "Short ranged AOE attack with 100% chance to interrupt casting",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 8,
            isAOE: true,
          },
          "Dragon Tail": {
            name: "Dragon Tail",
            reqPoints: 81,
            mpCost: 120,
            castTime: 0,
            cooldown: 60,
            duration: 0,
            description: "Frontal AOE cleave that deals a small amount of damage as recoil",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 5,
            isAOE: true,
          },
          "Fatal Scratch": {
            name: "Fatal Scratch",
            reqPoints: 90,
            mpCost: 175,
            castTime: 0,
            cooldown: 300,
            duration: 0,
            description: "A strong 360 AOE attack that deals damage as recoil if missed",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.CLEAVE,
            basePower: 7,
            isAOE: true,
          },
        },
      },
      {
        id: 4,
        name: "Bash",
        skills: {
          "Stun": {
            name: "Stun",
            reqPoints: 8,
            mpCost: 15,
            castTime: 0,
            cooldown: 8,
            duration: 0,
            description: "Attack + 30% chance to stun (blunt, 2H blunt, wand)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 1,
          },
          "Ground Shock": {
            name: "Ground Shock",
            reqPoints: 26,
            mpCost: 38,
            castTime: 0,
            cooldown: 18,
            duration: 0,
            description: "Attack + chance to interrupt casting (blunt, axe, wand)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 2,
          },
          "Stun Hammer": {
            name: "Stun Hammer",
            reqPoints: [
              { skillName: "Bash", points: 41 },
              { skillName: "Exorcism", points: 21 },
            ],
            mpCost: 30,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Attack and AOE stun (blunt, 2H blunt)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 2,
            isAOE: true,
          },
          "Shatter Armor": {
            name: "Shatter Armor",
            reqPoints: 50,
            mpCost: 30,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Attack with a chance to break enemy armor and interrupt casting (blunt, 2H blunt, wand)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 2,
          },
          "Shield Break": {
            name: "Shield Break",
            reqPoints: 61,
            mpCost: 22,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Knock target out of blocking or defensive march",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
          },
          "Subvert": {
            name: "Subvert",
            reqPoints: 71,
            mpCost: 69,
            castTime: 0.5,
            cooldown: 25,
            duration: 0,
            description: "Attack that scales with enemy defense",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 3,
          },
          "Rock Crash": {
            name: "Rock Crash",
            reqPoints: 81,
            mpCost: 120,
            castTime: 2.5,
            cooldown: 60,
            duration: 0,
            description: "Strong single target attack",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 5,
          },
        },
      },
      {
        id: 5,
        name: "Defend",
        skills: {
          "Blocking": {
            name: "Blocking",
            reqPoints: 8,
            mpCost: 5,
            castTime: 0,
            cooldown: 2,
            duration: 0,
            description: "Stationary blocking mode",
          },
          "Shield Bash": {
            name: "Shield Bash",
            reqPoints: 12,
            mpCost: 14,
            castTime: 0,
            cooldown: 10,
            duration: 2,
            description: "Trip enemies who attack you while blocking",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 1,
          },
          "Parapet": {
            name: "Parapet",
            reqPoints: 21,
            mpCost: 25,
            castTime: 2,
            cooldown: 30,
            duration: 120,
            description: "Increase critical hit resistance, lowers dodge",
            basePower: 1,
            isBuff: true,
          },
          "Auto-guard": {
            name: "Auto-guard",
            reqPoints: 26,
            mpCost: 20,
            castTime: 0,
            cooldown: 30,
            duration: 120,
            description: "Chance to reduce damage taken (shield)",
            basePower: 1,
            isBuff: true,
          },
          "Shield Charge": {
            name: "Shield Charge",
            reqPoints: 31,
            mpCost: 18,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Charge forward and knockdown enemies in your path",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.BASH,
            basePower: 1,
          },
          "Defensive March": {
            name: "Defensive March",
            reqPoints: 41,
            mpCost: 10,
            castTime: 0,
            cooldown: 5,
            duration: 0,
            description: "Move while blocking",
            isBuff: true,
          },
          "Guardian": {
            name: "Guardian",
            reqPoints: 54,
            mpCost: 16,
            castTime: 4,
            cooldown: 10,
            duration: 300,
            description: "Take all damage for a party member",
            basePower: 1,
            isBuff: true,
          },
          "Eternal Dirge": {
            name: "Eternal Dirge",
            reqPoints: 61,
            mpCost: 74,
            castTime: 0,
            cooldown: 20,
            duration: 0,
            description: "AOE that prevents all skills from being used while active",
            isAOE: true,
          },
        },
      },
    ],
  },
  6: {
    skills: [
      {
        id: 7,
        name: "Shot",
        skills: {
          "Flaming Arrow": {
            name: "Flaming Arrow",
            reqPoints: 8,
            mpCost: 12,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Ranged attack with a chance to burn (bow, crossbow)",
            damageType: DamageType.PHYSICAL,
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 1,
            // added hasDebuff property for skills with chance to debuff enemy
            // in this case, burn
            // burn cuts target atk in half
            hasDebuff: true,
          },
          "Cobra Arrow": {
            name: "Cobra Arrow",
            reqPoints: 12,
            mpCost: 12,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Ranged attack with a chance to poison (bow, crossbow)",
            damageType: DamageType.PHYSICAL,
            basePower: 1,
            // added hasDebuff property for skills with chance to debuff enemy
            // in this case, poison
            hasDebuff: true,
          },
          "Arrow Rain": {
            name: "Arrow Rain",
            reqPoints: 26,
            mpCost: 15,
            castTime: 1,
            cooldown: 5,
            duration: 0,
            description: "AOE attack over target (bow)",
            damageType: DamageType.PHYSICAL,
            basePower: 1,
            isAOE: true,
          },
          "Multi Shot": {
            name: "Multi Shot",
            reqPoints: [
              { skillName: "Shot", points: 41 },
              { skillName: "Trap", points: 21 },
            ],
            mpCost: 20,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Fire five arrows at once (crossbow)",
            damageType: DamageType.PHYSICAL,
            basePower: 1,
          },
          "Charge Shot": {
            name: "Charge Shot",
            reqPoints: [
              { skillName: "Shot", points: 50 },
              { skillName: "Trap", points: 21 },
            ],
            mpCost: 18,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Deal damage and knockback target (bow, crossbow)",
            damageType: DamageType.PHYSICAL,
            basePower: 1,
          },
          "Silence Arrow": {
            name: "Silence Arrow",
            reqPoints: 54,
            mpCost: 33,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Silence target (bow)",
            damageType: DamageType.PHYSICAL,
            basePower: 2,
            hasDebuff: true, // silence: can't cast spells. melee skills still work
          },
          "Arrow Storm": {
            name: "Arrow Storm",
            reqPoints: 61,
            mpCost: 15,
            castTime: 1,
            cooldown: 5,
            duration: 0,
            description: "AOE attack over target (bow), replaces Arrow Rain",
            basePower: 1,
            isAOE: true,
          },
          "Arrow Mastery (Passive)": {
            name: "Arrow Mastery (Passive)",
            reqPoints: 71,
            mpCost: 49,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Pin target in place if hit from the back (bow, crossbow)",
            isPassive: true,
          },
          "Piercing Shot": {
            name: "Piercing Shot",
            reqPoints: 81,
            mpCost: 22,
            castTime: 0,
            cooldown: 8,
            duration: 0,
            description: "Shoot an arrow that pierces the target",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.THRUST,
            basePower: 1,
          },
          "Cataract": {
            name: "Cataract",
            reqPoints: 90,
            mpCost: 54,
            castTime: 0,
            cooldown: 90,
            duration: 0,
            description: "Deal increased damage to the front of target, reduce damage taken from the front, but increase damage taken from the back. reduces movement speed",
            damageType: DamageType.PHYSICAL,
            basePower: 3,
          },
        },
      },
      {
        id: 8,
        name: "Alchemy",
        skills: {
          "Poison Making": {
            name: "Poison Making",
            reqPoints: 8,
            mpCost: 3,
            castTime: 1,
            cooldown: 0,
            duration: 0,
            description: "Creates Poison vials (Deadly Nightshade x1, Container x1)",
          },
          "Toxify": {
            name: "Toxify",
            reqPoints: 12,
            mpCost: 15,
            castTime: 2,
            cooldown: 10,
            duration: 120,
            description: "Coat weapon with poison",
            isBuff: true,
            selfBuffOnly: true,
            buffEffectTable: {
              weaponAura: {
                element: 'poison',
                formula: 'toxify',
              },
            },
          },
          "Serum": {
            name: "Serum",
            reqPoints: 26,
            mpCost: 3,
            castTime: 1,
            cooldown: 0,
            duration: 0,
            description: "Create an antidote to remove poison (Antidote Herb x1, Container x1)",
          },
          "Potion Crafting": {
            name: "Potion Crafting",
            reqPoints: 41,
            mpCost: 3,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Create a mysterious potion to cure disease, silence, and burn (Moonlight Herb x1, Aquilegia x1, Container x1)",
          },
          "Befuddle": {
            name: "Befuddle",
            reqPoints: 50,
            mpCost: 31,
            castTime: 0,
            cooldown: 0,
            duration: 150,
            description: "Strike to reduce target's casting speed",
            isDebuff: true,
            debuffEffectTable: {
              castSpeedDown: 0.15,
            },
          },
          "Toxic Aura (Passive)": {
            name: "Toxic Aura (Passive)",
            reqPoints: 61,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Increased damage with poison when using Toxify",
            isPassive: true,
          },
          "Surveillance": {
            name: "Surveillance",
            reqPoints: 71,
            mpCost: 44,
            castTime: 0.5,
            cooldown: 20,
            duration: 10,
            description: "See enemy traps for 10 seconds",
          },
          "Seudoro-ga": {
            name: "Seudoro-ga",
            reqPoints: 81,
            mpCost: 1,
            castTime: 0,
            cooldown: 60,
            duration: 30,
            description: "Drink a mysterious potion to gain a temporary buff, increase accuracy, prevent taking critical hits",
            basePower: 1,
          },
          "Overdose": {
            name: "Overdose",
            reqPoints: 90,
            mpCost: 25,
            castTime: 0,
            cooldown: 45,
            duration: 0,
            description: "Drinking a potion will heal the party for a large amount",
          },
        },
      },
      {
        id: 9,
        name: "Assassination",
        skills: {
          "Backstab": {
            name: "Backstab",
            reqPoints: 8,
            mpCost: 15,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Attack enemy from behind",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Dagger Throw": {
            name: "Dagger Throw",
            reqPoints: 12,
            mpCost: 10,
            castTime: 0,
            cooldown: 5,
            duration: 0,
            description: "Throw a dagger at target (dagger)",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Rush": {
            name: "Rush",
            reqPoints: 26,
            mpCost: 30,
            castTime: 0,
            cooldown: 90,
            duration: 20,
            description: "Each attack hits twice, caster takes more damage (dagger, knuckles)",
            isBuff: true,
          },
          "Blindside": {
            name: "Blindside",
            reqPoints: 41,
            mpCost: 15,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "While cloaked, trips target, does not remove cloak",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Pierce Armor": {
            name: "Pierce Armor",
            reqPoints: 54,
            mpCost: 15,
            castTime: 0,
            cooldown: 10,
            duration: 0,
            description: "Attack that ignores armor, bonus damage against knocked down targets",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 1,
          },
          "Double-Cross": {
            name: "Double-Cross",
            reqPoints: 71,
            mpCost: 58,
            castTime: 0,
            cooldown: 55,
            duration: 0,
            description: "Attack back of target to reset all skill cooldowns (dagger, knuckles), only against other players",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 3,
          },
          "Killing Time": {
            name: "Killing Time",
            reqPoints: 81,
            mpCost: 20,
            castTime: 0,
            cooldown: 15,
            duration: 0,
            description: "Can be used while hiding, deals a heavy blow from behind",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 3,
          },
          "Overkill": {
            name: "Overkill",
            reqPoints: 90,
            mpCost: 70,
            castTime: 0,
            cooldown: 60,
            duration: 0,
            description: "Killed target cannot be revived",
            damageType: DamageType.PHYSICAL,
            damageSubType: PhysicalDamageSubType.SLASH,
            basePower: 3,
          },
        },
      },
      {
        id: 10,
        name: "Trap",
        skills: {
          "Disarm": {
            name: "Disarm",
            reqPoints: 8,
            mpCost: 10,
            castTime: 1,
            cooldown: 10,
            duration: 0,
            description: "Remove nearby traps",
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
          },
          "Tangled Legs": {
            name: "Tangled Legs",
            reqPoints: 16,
            mpCost: 20,
            castTime: 1.5,
            cooldown: 3,
            duration: 0,
            description: "Root target for 3 seconds (Trap x1)",
          },
          "Plant Mine": {
            name: "Plant Mine",
            reqPoints: 26,
            mpCost: 30,
            castTime: 1.5,
            cooldown: 3,
            duration: 0,
            description: "Plant a mine that explodes on target (Trap x1)",
            damageType: DamageType.MAGICAL,
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 2,
          },
          "Worm Bomb": {
            name: "Worm Bomb",
            reqPoints: 41,
            mpCost: 33,
            castTime: 3,
            cooldown: 5,
            duration: 0,
            description: "Trap that crawls forward and explodes on target (Trap x1)",
            damageType: DamageType.MAGICAL,
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 2,
          },
          "Safe Zone": {
            name: "Safe Zone",
            reqPoints: 50,
            mpCost: 46,
            castTime: 1.5,
            cooldown: 8,
            duration: 0,
            description: "Create a field that prevents field spells from being used or doing damage",
            isAOE: true,
            isBuff: true,
            aoeTargetMode: AOETargetMode.SELF_CENTERED,
          },
          "Stone Prison": {
            name: "Stone Prison",
            reqPoints: 61,
            mpCost: 48,
            castTime: 1.5,
            cooldown: 3,
            duration: 0,
            description: "Create a stone prison around mounted target (Trap x1)",
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
          },
          "Mind Warp": {
            name: "Mind Warp",
            reqPoints: 71,
            mpCost: 48,
            castTime: 1.5,
            cooldown: 3,
            duration: 0,
            description: "Trap that reduces target's MP (Trap x1)",
            damageType: DamageType.MAGICAL,
          },
          "Poison Bomb": {
            name: "Poison Bomb",
            reqPoints: 81,
            mpCost: 48,
            castTime: 8,
            cooldown: 3,
            duration: 0,
            description: "Trap that explodes on target, deals damage and poisons (Trap x1)",
            damageType: DamageType.MAGICAL,
            basePower: 2,
          },
          "Oil Bomb": {
            name: "Oil Bomb",
            reqPoints: 90,
            mpCost: 62,
            castTime: 6,
            cooldown: 30,
            duration: 0,
            description: "Trap that moves forward and explodes on target, deals damage (Trap x1)",
            damageType: DamageType.MAGICAL,
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 3,
          },
        },
      },
      {
        id: 11,
        name: "Dodge",
        skills: {
          "Backstep": {
            name: "Backstep",
            reqPoints: 3,
            mpCost: 5,
            castTime: 0,
            cooldown: 3,
            duration: 1,
            description: "Step back and increase dodge by 100 for 1 second",
            isBuff: true,
          },
          "Dash": {
            name: "Dash",
            reqPoints: 8,
            mpCost: 18,
            castTime: 0,
            cooldown: 30,
            duration: 2,
            description: "Dash forward",
          },
          "Quick Step": {
            name: "Quick Step",
            reqPoints: 16,
            mpCost: 35,
            castTime: 0.5,
            cooldown: 90,
            duration: 60,
            description: "Increased dodge",
          },
          "Tangled Fingers": {
            name: "Tangled Fingers",
            reqPoints: 21,
            mpCost: 22,
            castTime: 0.8,
            cooldown: 30,
            duration: 30,
            description: "Reduce target's accuracy",
            isDebuff: true,
            debuffEffectTable: {
              accuracyDown: 0.15,
            },
          },
          "Reinforce (Passive)": {
            name: "Reinforce (Passive)",
            reqPoints: 26,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Knockdown/Knockback/Freeze resistance",
            isPassive: true,
          },
          "Avoidance": {
            name: "Avoidance",
            reqPoints: 41,
            mpCost: 38,
            castTime: 0.5,
            cooldown: 30,
            duration: 0,
            description: "Increased dodge until hit by two physical attacks",
            isBuff: true,
          },
          "Intuition (Passive)": {
            name: "Intuition (Passive)",
            reqPoints: 50,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Chance to dodge magic",
            isPassive: true,
          },
          "Bolster": {
            name: "Bolster",
            reqPoints: 66,
            mpCost: 29,
            castTime: 1,
            cooldown: 1.5,
            duration: 2,
            description: "Cast Dash on target",
          },
          "Move Stream": {
            name: "Move Stream",
            reqPoints: 81,
            mpCost: 60,
            castTime: 0,
            cooldown: 25,
            duration: 2,
            description: "Cast Dash on all party members in range",
            isBuff: true,
            isAOE: true,
          },
          "Sprint": {
            name: "Sprint",
            reqPoints: 90,
            mpCost: 18,
            castTime: 0,
            cooldown: 30,
            duration: 2,
            description: "Dash forward",
          },
          "Spurt": {
            name: "Spurt",
            reqPoints: 90,
            mpCost: 18,
            castTime: 0,
            cooldown: 30,
            duration: 2,
            description: "Dash forward",
          },
        },
      },
    ],
  },
  12: {
    skills: [
      {
        id: 13,
        name: "Grace",
        skills: {
          "First Aid": {
            name: "First Aid",
            reqPoints: 8,
            mpCost: 28,
            castTime: 1,
            cooldown: 4,
            duration: 0,
            description: "Restore HP based on level, expertise, and INT",
          },
          "Cleanse": {
            name: "Cleanse",
            reqPoints: 12,
            mpCost: 15,
            castTime: 1,
            cooldown: 3,
            duration: 0,
            description: "Cure Poison",
          },
          "Regenerate": {
            name: "Regenerate",
            reqPoints: 21,
            mpCost: 40,
            castTime: 1.5,
            cooldown: 5,
            duration: 120,
            description: "Every few seconds, restore HP based on SPI and expertise",
          },
          "Vivify": {
            name: "Vivify",
            reqPoints: 26,
            mpCost: 18,
            castTime: 1,
            cooldown: 3,
            duration: 0,
            description: "Cure sleep/knock out/freeze",
          },
          "Revive": {
            name: "Revive",
            reqPoints: 34,
            mpCost: 60,
            castTime: 5,
            cooldown: 60,
            duration: 0,
            isRevive: true,
            description: "Revive a fallen ally, restoring them with partial HP",
          },
          "Restoration": {
            name: "Restoration",
            reqPoints: 41,
            mpCost: 90,
            castTime: 3,
            cooldown: 20,
            duration: 120,
            description: "Restore party HP over time based on level, expertise, and INT",
          },
          "Healing Aura": {
            name: "Healing Aura",
            reqPoints: 54,
            mpCost: 256,
            castTime: 2,
            cooldown: 30,
            duration: 0,
            description: "Heal party members in range",
            isAOE: true,
          },
          "Purify": {
            name: "Purify",
            reqPoints: 71,
            mpCost: 76,
            castTime: 1.5,
            cooldown: 35,
            duration: 15,
            description: "Cures all debuffs and increases resistance to debuffs for 15 seconds",
          },
          "Sacrifice": {
            name: "Sacrifice",
            reqPoints: 81,
            mpCost: 0,
            castTime: 0,
            cooldown: 300,
            duration: 0,
            description: "Sacrifice self to restore a party member's HP, consumes 5 Holy Waters",
          },
        },
      },
      {
        id: 14,
        name: "Blessing",
        skills: {
          "Velox": {
            name: "Velox",
            reqPoints: 8,
            mpCost: 26,
            castTime: 0.5,
            cooldown: 1.5,
            duration: 480,
            description: "Increase player's attack speed",
            basePower: 2,
          },
          "Lapis Mediow": {
            name: "Lapis Mediow",
            reqPoints: 12,
            mpCost: 22,
            castTime: 0.5,
            cooldown: 1.5,
            duration: 480,
            buffEffectTable: {
              spiValues: [
                {
                  value: 33,
                  Blessing: [
                    { value: 24.9, def: 5 },
                    { value: 25, def: 6 },
                    { value: 50, def: 7 },
                    { value: 75, def: 8 },
                  ],
                },
                {
                  value: 34,
                  Blessing: [
                    { value: 24.9, def: 6 },
                    { value: 25, def: 7 },
                    { value: 50, def: 8 },
                    { value: 75, def: 9 },
                  ],
                },
                {
                  value: 67,
                  Blessing: [
                    { value: 24.9, def: 7 },
                    { value: 25, def: 8 },
                    { value: 50, def: 9 },
                    { value: 75, def: 10 },
                  ],
                },
                {
                  value: 100,
                  Blessing: [
                    { value: 24.9, def: 8 },
                    { value: 25, def: 9 },
                    { value: 50, def: 10 },
                    { value: 75, def: 11 },
                  ],
                },
                {
                  value: 134,
                  Blessing: [
                    { value: 24.9, def: 9 },
                    { value: 25, def: 10 },
                    { value: 50, def: 11 },
                    { value: 75, def: 12 },
                  ],
                },
              ],
            },
            description: "Increase player's defense",
          },
          "Impedimentia": {
            name: "Impedimentia",
            reqPoints: 21,
            mpCost: 33,
            castTime: 1.5,
            cooldown: 10,
            duration: 10,
            description: "Reduce target's movement speed",
            isDebuff: true,
            debuffEffectTable: {
              speedDown: 0.15,
            },
          },
          "Group Barrier": {
            name: "Group Barrier",
            reqPoints: 26,
            mpCost: 70,
            castTime: 1,
            cooldown: 1.5,
            duration: 120,
            buffEffectTable: {
              physicalDamageReduction: 'formula:(10 + blessing / 5) / 100',
            },
            description: "Physical damage reduction on all party members in range. Reduction based on caster's Blessing proficiency",
            isAOE: true,
          },
          "Aqua Elimus": {
            name: "Aqua Elimus",
            reqPoints: 41,
            mpCost: 4,
            castTime: 1,
            cooldown: 0,
            duration: 0,
            description: "Craft one Holy Water (Container x1)",
          },
          "Saltio": {
            name: "Saltio",
            reqPoints: 54,
            mpCost: 37,
            castTime: 0,
            cooldown: 5,
            duration: 90,
            buffEffectTable: {
              castTime: -50,
            },
            description: "Cut base cast time of all skills by 50%",
          },
          "Battle Prayer": {
            name: "Battle Prayer",
            reqPoints: 61,
            mpCost: 78,
            castTime: 0.5,
            cooldown: 1.5,
            duration: 480,
            buffEffectTable: {
              str: 9,
              agi: 9,
              int: 9,
            },
            description: "Increase player's STR, AGI, and INT",
          },
          "Locomitigation": {
            name: "Locomitigation",
            reqPoints: 81,
            mpCost: 100,
            castTime: 1,
            cooldown: 10,
            duration: 120,
            description: "Reduce party members' critical damage taken",
          },
          "Spirit Protection": {
            name: "Spirit Protection",
            reqPoints: 90,
            mpCost: 143,
            castTime: 1,
            cooldown: 30,
            duration: 90,
            description: "Reduce party members' aura damage taken",
          },
        },
      },
      {
        id: 15,
        name: "Exorcism",
        skills: {
          "Pure Arrow": {
            name: "Pure Arrow",
            reqPoints: 8,
            mpCost: 18,
            castTime: 1,
            cooldown: 5,
            duration: 0,
            description: "Shoot a holy projectile",
            damageType: DamageType.MAGICAL,
            damageSubType: MagicalDamageSubType.HOLY,
            basePower: 1,
          },
          "Elemental Absorption": {
            name: "Elemental Absorption",
            reqPoints: 12,
            mpCost: 60,
            castTime: 0.8,
            cooldown: 10,
            duration: 1,
            description: "Reduce elemental damage taken",
            basePower: 3,
          },
          "Bless Weapon": {
            name: "Bless Weapon",
            reqPoints: 26,
            mpCost: 30,
            castTime: 1.5,
            cooldown: 1.5,
            duration: 480,
            description: "Embue weapon with holy aura",
            buffEffectTable: {
              weaponAura: {
                element: 'holy',
                spiTiers: [
                  { spi: 0, min: 4, max: 5 },
                  { spi: 17, min: 6, max: 7 },
                  { spi: 34, min: 7, max: 9 },
                  { spi: 50, min: 9, max: 12 },
                  { spi: 67, min: 12, max: 16 },
                  { spi: 84, min: 15, max: 20 },
                  { spi: 100, min: 18, max: 24 },
                  { spi: 117, min: 23, max: 30 },
                  { spi: 134, min: 27, max: 36 },
                ],
              },
            },
          },
          "Remedium": {
            name: "Remedium",
            reqPoints: 41,
            mpCost: 26,
            castTime: 1,
            cooldown: 5,
            duration: 0,
            description: "Dispel a single disorder",
          },
          "Holy Rays": {
            name: "Holy Rays",
            reqPoints: 54,
            mpCost: 132,
            castTime: 6,
            cooldown: 60,
            duration: 0,
            isAOE: true,
            description: "Rain holy beams from above",
            damageSubType: MagicalDamageSubType.HOLY,
            basePower: 6,
          },
          "Banish": {
            name: "Banish",
            reqPoints: 61,
            mpCost: 0,
            castTime: 5,
            cooldown: 10,
            duration: 0,
            isAOE: true,
            description: "Banish a summoned object or monster",
          },
          "Devotion": {
            name: "Devotion",
            reqPoints: [
              { skillName: "Exorcism", points: 61 },
              { skillName: "Blessing", points: 26 },
            ],
            mpCost: 50,
            castTime: 3,
            cooldown: 0.5,
            duration: 300,
            description: "All MP costs of targeted party member are taken from your MP pool",
          },
          "Silent Void": {
            name: "Silent Void",
            reqPoints: 61,
            mpCost: 93,
            castTime: 5,
            cooldown: 12,
            duration: 120,
            isAOE: true,
            description: "Create a field that negates all field spells, targeted and non-targeted",
          },
          "Twinkle Extreme": {
            name: "Twinkle Extreme",
            reqPoints: 81,
            mpCost: 110,
            castTime: 3,
            cooldown: 10,
            duration: 0,
            description: "Implant a holy bomb in target, delayed explosion does large damage based on INT",
            basePower: 5,
          },
          "Abstention": {
            name: "Abstention",
            reqPoints: 90,
            mpCost: 77,
            castTime: 3,
            cooldown: 60,
            duration: 0,
            description: "Prevent target from using field spells until debuff expires",
          },
        },
      },
      {
        id: 16,
        name: "Hymn",
        skills: {
          "Green Song": {
            name: "Green Song",
            reqPoints: 8,
            mpCost: 30,
            castTime: 0,
            cooldown: 5,
            duration: 0,
            buffEffectTable: {
              spiValues: [
                {
                  value: 33,
                  Blessing: [
                    { value: 8, dodgeChance: 1 },
                    { value: 16, dodgeChance: 2 },
                    { value: 24, dodgeChance: 3 },
                    { value: 31, dodgeChance: 4 },
                    { value: 39, dodgeChance: 5 },
                    { value: 47, dodgeChance: 6 },
                    { value: 54, dodgeChance: 7 },
                    { value: 62, dodgeChance: 8 },
                  ],
                },
              ],
            },
            description: "Increase accuracy and dodge for those in song range",
            isAOE: true,
          },
          "Luminous Chant (Passive)": {
            name: "Luminous Chant (Passive)",
            reqPoints: 12,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Gain ability to move while chanting",
            isPassive: true,
          },
          "Blue Song": {
            name: "Blue Song",
            reqPoints: [
              { skillName: "Hymn", points: 30 },
              { skillName: "Blessing", points: 71 },
            ],
            mpCost: 33,
            castTime: 0,
            cooldown: 5,
            duration: 0,
            description: "Increase magical damage and decrease skill cooldowns for all in song range",
            basePower: 2,
            isAOE: true,
          },
          "Yellow Song": {
            name: "Yellow Song",
            reqPoints: [
              { skillName: "Hymn", points: 20 },
              { skillName: "Grace", points: 61 },
            ],
            mpCost: 33,
            castTime: 0,
            cooldown: 5,
            duration: 0,
            description: "Players in song range gain immunity to damage below a certain threshold",
            basePower: 2,
            isAOE: true,
          },
          "Red Song": {
            name: "Red Song",
            reqPoints: [
              { skillName: "Hymn", points: 30 },
              { skillName: "Exorcism", points: 30 },
            ],
            mpCost: 100,
            castTime: 0,
            cooldown: 6,
            duration: 0,
            description: "Damage LP and MP for all enemies in range",
            basePower: 2,
            isAOE: true,
          },
        },
      },
    ],
  },
  17: {
    skills: [
      {
        id: 18,
        name: "Elemental",
        skills: {
          "Hailstone": {
            name: "Hailstone",
            reqPoints: 8,
            mpCost: 18,
            castTime: 0.3,
            cooldown: 2,
            duration: 4,
            description: "Hurl a ball of ice at the enemy, dealing ice damage",
            damageSubType: MagicalDamageSubType.ICE,
            basePower: 0.1,
          },
          "Thunder Ball": {
            name: "Thunder Ball",
            reqPoints: 12,
            mpCost: 50,
            castTime: 2,
            cooldown: 5,
            duration: 0,
            description: "Launch a ball of lightning that damages all enemies in range",
            damageSubType: MagicalDamageSubType.LIGHTNING,
            basePower: 1.4,
            isAOE: true,
          },
          "Ice Spear": {
            name: "Ice Spear",
            reqPoints: 21,
            mpCost: 59,
            castTime: 1.5,
            cooldown: 5,
            duration: 0,
            description: "Hurl a spear of ice at the enemy, dealing ice damage",
            damageSubType: MagicalDamageSubType.ICE,
            basePower: 3,
          },
          "Firestorm": {
            name: "Firestorm",
            reqPoints: 26,
            mpCost: 100,
            castTime: 6,
            cooldown: 30,
            duration: 5,
            description: "Summon a firestorm that damages all enemies in range",
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 3,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 6,
          },
          "Resist Fire": {
            name: "Resist Fire",
            reqPoints: 33,
            mpCost: 32,
            castTime: 1.5,
            cooldown: 3.5,
            duration: 20,
            description: "Reduce fire damage taken, increase ice and lightning damage taken",
            basePower: 0,
            buffEffectTable: {
              resistMods: { fire: 25, ice: -50, lightning: -50 },
            },
          },
          "Resist Ice": {
            name: "Resist Ice",
            reqPoints: 35,
            mpCost: 32,
            castTime: 1.5,
            cooldown: 3.5,
            duration: 20,
            description: "Reduce ice damage taken, increase fire and lightning damage taken",
            basePower: 0,
            buffEffectTable: {
              resistMods: { ice: 25, fire: -50, lightning: -50 },
            },
          },
          "Resist Lightning": {
            name: "Resist Lightning",
            reqPoints: 41,
            mpCost: 32,
            castTime: 1.5,
            cooldown: 3.5,
            duration: 20,
            description: "Reduce lightning damage taken, increase fire and ice damage taken",
            basePower: 0,
            buffEffectTable: {
              resistMods: { lightning: 25, fire: -50, ice: -50 },
            },
          },
          "Ice Storm": {
            name: "Ice Storm",
            reqPoints: 54,
            mpCost: 112,
            castTime: 7.5,
            cooldown: 20,
            duration: 3,
            description: "Summon a storm of ice that damages all enemies in range",
            damageSubType: MagicalDamageSubType.ICE,
            basePower: 1,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 6,
            pulseCount: 3,
            pulseInterval: 1000,
          },
          "Delay Bomb": {
            name: "Delay Bomb",
            reqPoints: 61,
            mpCost: 61,
            castTime: 2,
            cooldown: 6,
            duration: 0,
            description: "Implant a bomb in target, delayed explosion does large damage based on INT",
            basePower: 2,
          },
          "Thunderstorm": {
            name: "Thunderstorm",
            reqPoints: [
              { skillName: "Elemental", points: 61 },
              { skillName: "Exorcism", points: 40 },
            ],
            mpCost: 227,
            castTime: 20,
            cooldown: 20,
            duration: 0,
            description: "Call down a storm of lightning bolts in an area",
            damageSubType: MagicalDamageSubType.LIGHTNING,
            basePower: 4,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 8,
            pulseCount: 10,
            pulseInterval: 1000,
          },
          "Meteor Storm": {
            name: "Meteor Storm",
            reqPoints: [
              { skillName: "Elemental", points: 61 },
              { skillName: "Invocation", points: 40 },
            ],
            mpCost: 312,
            castTime: 20,
            cooldown: 20,
            duration: 0,
            description: "Unleash a massive meteor storm, dealing heavy damage to all enemies nearby",
            basePower: 4,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 10,
            pulseCount: 10,
            pulseInterval: 1000,
          },
          "Despair Swamp": {
            name: "Despair Swamp",
            reqPoints: [
              { skillName: "Elemental", points: 61 },
              { skillName: "Confusion", points: 40 },
            ],
            mpCost: 256,
            castTime: 21,
            cooldown: 20,
            duration: 0,
            description: "Summon a swamp that damages, slows, and poisons all enemies in range",
            damageSubType: MagicalDamageSubType.DARK,
            basePower: 2,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 7,
            pulseCount: 12,
            pulseInterval: 1000,
          },
          "Ice Tempest": {
            name: "Ice Tempest",
            reqPoints: 71,
            mpCost: 287,
            castTime: 7.5,
            cooldown: 20,
            duration: 0,
            description: "Summon a storm of ice that damages all enemies in range",
            damageSubType: MagicalDamageSubType.ICE,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 8,
            basePower: 5,
            pulseCount: 10,
            pulseInterval: 1000,
          },
          "Cremation": {
            name: "Cremation",
            reqPoints: 81,
            mpCost: 650,
            castTime: 4,
            cooldown: 50,
            duration: 0,
            description: "Big damage to all enemies in range",
            damageSubType: MagicalDamageSubType.FIRE,
            basePower: 3,
            isAOE: true,
          },
          "Glitter Discharge": {
            name: "Glitter Discharge",
            reqPoints: 90,
            mpCost: 132,
            castTime: 1,
            cooldown: 120,
            duration: 0,
            description: "Lightning shield on caster",
          },
        },
      },
      {
        id: 19,
        name: "Invocation",
        skills: {
          "Soul Bright": {
            name: "Soul Bright",
            reqPoints: 8,
            mpCost: 14,
            castTime: 1,
            cooldown: 6,
            duration: 0,
            description: "Reveal nearby invisible enemies",
          },
          "Mana Shield": {
            name: "Mana Shield",
            reqPoints: 21,
            mpCost: 24,
            castTime: 3,
            cooldown: 10,
            duration: 0,
            description: "Damage taken is reduced, taking some damage as MP",
            basePower: 1,
          },
          "Clear Mind": {
            name: "Clear Mind",
            reqPoints: 31,
            mpCost: 59,
            castTime: 5,
            cooldown: 1.5,
            duration: 80,
            description: "Increased spell interrupt resistance",
          },
          "Psychic Blades": {
            name: "Psychic Blades",
            reqPoints: 41,
            mpCost: 39,
            castTime: 3.5,
            cooldown: 10,
            duration: 0,
            description: "Release 3 blades of energy that damage all enemies in their path. Deals bonus damage based on enemy defense",
            basePower: 2,
            isAOE: true,
          },
          "Summon Wall": {
            name: "Summon Wall",
            reqPoints: 50,
            mpCost: 79,
            castTime: 5,
            cooldown: 90,
            duration: 180,
            description: "Create a wall that blocks all damage",
            basePower: 4,
          },
          "Summon Sandman": {
            name: "Summon Sandman",
            reqPoints: 61,
            mpCost: 58,
            castTime: 7,
            cooldown: 30,
            duration: 10,
            description: "Summon a sandstorm that knocks back enemies, sleeping, and damaging them",
            basePower: 3,
          },
          "Summon Plant": {
            name: "Summon Plant",
            reqPoints: 71,
            mpCost: 192,
            castTime: 2,
            cooldown: 60,
            duration: 180,
            description: "Summon an elemental plant that damages all enemies in range. Element depends on weapon enhancement (+5 = 50, +8 = 70)",
            basePower: 8,
            isAOE: true,
          },
          "Regia Pureizu": {
            name: "Regia Pureizu",
            reqPoints: [
              { skillName: "Invocation", points: 78 },
              { skillName: "Elemental", points: 40 },
            ],
            mpCost: 60,
            castTime: 1.5,
            cooldown: 1.5,
            duration: 60,
            description: "Revive a fallen ally",
          },
          "Summon Wyvern": {
            name: "Summon Wyvern",
            reqPoints: 81,
            mpCost: 520,
            castTime: 10,
            cooldown: 60,
            duration: 60,
            description: "Summon a wyvern that damages all enemies in range",
            basePower: 21,
            isAOE: true,
          },
          "Summon Turtle": {
            name: "Summon Turtle",
            reqPoints: 90,
            mpCost: 700,
            castTime: 15,
            cooldown: 300,
            duration: 0,
            description: "Summon a turtle that damages all enemies in range",
            basePower: 28,
            isAOE: true,
          },
        },
      },
      {
        id: 20,
        name: "Darkness",
        skills: {
          "Poison": {
            name: "Poison",
            reqPoints: 8,
            mpCost: 24,
            castTime: 2,
            cooldown: 5,
            duration: 60,
            description: "Poison the target, dealing damage over time",
            isDebuff: true,
            debuffDuration: 60,
            debuffEffectTable: {
              dot: 'poison',
              dotPotency: 0,
              dotTickInterval: 2000,
              dotSPIBase: 0.05,
              dotSPIMax: 0.10,
              dotSPICap: 110,
            },
          },
          "Gloom": {
            name: "Gloom",
            reqPoints: 12,
            mpCost: 38,
            castTime: 2,
            cooldown: 10,
            duration: 120,
            description: "Embue weapon with dark aura, damaging yourself with recoil",
            damageSubType: MagicalDamageSubType.DARK,
            isBuff: true,
            selfBuffOnly: true,
            buffEffectTable: {
              weaponAura: {
                element: 'dark',
                spiTiers: [
                  { spi: 0, min: 16, max: 16 },
                  { spi: 17, min: 26, max: 26 },
                  { spi: 34, min: 47, max: 47 },
                  { spi: 50, min: 69, max: 69 },
                  { spi: 67, min: 82, max: 82 },
                  { spi: 84, min: 100, max: 100 },
                  { spi: 100, min: 110, max: 110 },
                  { spi: 117, min: 120, max: 120 },
                  { spi: 134, min: 150, max: 150 },
                ],
              },
            },
          },
          "Blood Drain": {
            name: "Blood Drain",
            reqPoints: 21,
            mpCost: 32,
            castTime: 1,
            cooldown: 10,
            duration: 0,
            description: "Drain life from the target and heal yourself",
          },
          "Mind Venom": {
            name: "Mind Venom",
            reqPoints: 26,
            mpCost: 33,
            castTime: 2.5,
            cooldown: 10,
            duration: 0,
            description: "Poison the target's mind, dealing damage over time",
            isDebuff: true,
            debuffDuration: 30,
            debuffEffectTable: {
              dot: 'severe_poison',
              dotPotency: 0,
              dotTickInterval: 3000,
              dotMpDrain: 5,
              dotSPIBase: 0.10,
              dotSPIMax: 0.15,
              dotSPICap: 110,
            },
          },
          "Dispel": {
            name: "Dispel",
            reqPoints: 33,
            mpCost: 26,
            castTime: 1,
            cooldown: 15,
            duration: 0,
            description: "Dispel a buff from target",
          },
          "Resist Malice": {
            name: "Resist Malice",
            reqPoints: 35,
            mpCost: 32,
            castTime: 1.5,
            cooldown: 3.5,
            duration: 20,
            description: "Reduce dark damage taken, greatly reducing charm resistance",
            basePower: 2,
            isBuff: true,
            buffEffectTable: {
              resistMods: { dark: 25, charm: -50 },
            },
          },
          "Undermine": {
            name: "Undermine",
            reqPoints: 41,
            mpCost: 26,
            castTime: 0.5,
            cooldown: 10,
            duration: 0,
            description: "Increase damage of the next attack on target",
            isDebuff: true,
            debuffDuration: 8,
            debuffEffectTable: {
              damageTakenUp: 0.25,
              consumable: true,
            },
          },
          "Pestilence": {
            name: "Pestilence",
            reqPoints: 54,
            mpCost: 62,
            castTime: 1,
            cooldown: 10,
            duration: 0,
            description: "Deal poison damage to all enemies in range",
            basePower: 3,
            isAOE: true,
            hasDebuff: true, // hits 3 times in the area. poisons on any of the 3 attack ticks
            debuffDuration: 10,
          },
          "Equalize (Passive)": {
            name: "Equalize (Passive)",
            reqPoints: 61,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Chance to remove a buff from target on hit",
            isPassive: true,
          },
          "Dark Frenzy": {
            name: "Dark Frenzy",
            reqPoints: 71,
            mpCost: 122,
            castTime: 3,
            cooldown: 10,
            duration: 6,
            description: "Summon darkness from the abyss to damage all enemies in range",
            damageSubType: MagicalDamageSubType.DARK,
            basePower: 5,
            isAOE: true,
            hasDebuff: true, // weaken: set all hit target elemental resistances to 0.
            // 50 lightning res -> 0.
            debuffDuration: 6, // seconds
          },
          "Ramkyado": {
            name: "Ramkyado",
            reqPoints: [
              { skillName: "Darkness", points: 78 },
              { skillName: "Slash", points: 26 },
            ],
            mpCost: 15,
            castTime: 0,
            cooldown: 8,
            duration: 0,
            description: "Slice enemy with weapon",
            basePower: 1,
          },
          "Bind Criminal": {
            name: "Bind Criminal",
            reqPoints: 81,
            mpCost: 30,
            castTime: 0,
            cooldown: 90,
            duration: 0,
            description: "Bind targets in large AOE, preventing them from moving",
            isAOE: true,
          },
          "Sins Genocide": {
            name: "Sins Genocide",
            reqPoints: 90,
            mpCost: 48,
            castTime: 0,
            cooldown: 30,
            duration: 0,
            description: "Use the magic sword called from the abyss to skewer your opponent",
            damageSubType: MagicalDamageSubType.HOLY,
            basePower: 2,
          },
        },
      },
      {
        id: 21,
        name: "Confusion",
        skills: {
          "Weakness": {
            name: "Weakness",
            reqPoints: 8,
            mpCost: 18,
            castTime: 1,
            cooldown: 5,
            duration: 120,
            description: "Reduce target's attack",
            isDebuff: true,
            debuffEffectTable: {
              debuffCategory: 'disorder',
              attackDown: 0.15,
            },
          },
          "Sandstorm": {
            name: "Sandstorm",
            reqPoints: 12,
            mpCost: 51,
            castTime: 2,
            cooldown: 20,
            duration: 20,
            description: "Summon a sandstorm that puts target to sleep",
            basePower: 3,
            debuffEffectTable: {
              
            }
          },
          "Psionic Blast": {
            name: "Psionic Blast",
            reqPoints: 21,
            mpCost: 25,
            castTime: 1.5,
            cooldown: 5,
            duration: 0,
            description: "Deal damage to target's MP",
            basePower: 1,
          },
          "Weaken": {
            name: "Weaken",
            reqPoints: 26,
            mpCost: 18,
            castTime: 1,
            cooldown: 5,
            duration: 120,
            description: "Reduce target's defense",
            isDebuff: true,
            debuffEffectTable: {
              debuffCategory: 'disorder',
              defenseDown: 0.15,
            },
          },
          "Impede": {
            name: "Impede",
            reqPoints: 33,
            mpCost: 28,
            castTime: 2,
            cooldown: 5,
            duration: 120,
            description: "Reduce target's dodge",
            debuffEffectTable: {
              debuffCategory: 'ailment',
            }
          },
          "Resist Charm": {
            name: "Resist Charm",
            reqPoints: 35,
            mpCost: 32,
            castTime: 1.5,
            cooldown: 3.5,
            duration: 7,
            description: "Increase charm resistance, greatly reducing dark resistance",
            buffEffectTable: {
              resistMods: { charm: 25, dark: -50 },
            },
          },
          "Icy Strike": {
            name: "Icy Strike",
            reqPoints: 41,
            mpCost: 44,
            castTime: 0.3,
            cooldown: 12,
            duration: 15,
            description: "Freeze target, slowing them",
            damageSubType: MagicalDamageSubType.ICE,
            basePower: 1,
            debuffEffectTable: {
              debuffCategory: 'ailment',
              hasFreeze: {
                duration: 5
              },
              moveSpeedDown: 0.3
            }
          },
          "Wasteland": {
            name: "Wasteland",
            reqPoints: 54,
            mpCost: 44,
            castTime: 0.5,
            cooldown: 30,
            duration: 30,
            description: "Summon a poion wasteland that damages and slows all enemies in range",
            basePower: 2,
            isAOE: true,
            aoeTargetMode: AOETargetMode.GROUND_TARGETED,
            aoeRadius: 8,
            debuffEffectTable: {
              dot: 'poison',
              dotPotency: 0,
              dotTickInterval: 2000,
              dotSPIBase: 0.05,
              dotSPIMax: 0.10,
              dotSPICap: 110,
              moveSpeedDown: 0.5
            },
          },
          "Siren Storm": {
            name: "Siren Storm",
            reqPoints: 61,
            mpCost: 87,
            castTime: 4.5,
            cooldown: 15,
            duration: 0,
            description: "Damage MP of all enemies in AOE",
            basePower: 4,
            isAOE: true,
          },
          "Cursed Bolt": {
            name: "Cursed Bolt",
            reqPoints: 71,
            mpCost: 69,
            castTime: 2,
            cooldown: 20,
            duration: 0,
            description: "Curse target, preventing resurrection",
            damageSubType: MagicalDamageSubType.DARK,
            basePower: 3,
          },
          "Hallucination": {
            name: "Hallucination",
            reqPoints: 90,
            mpCost: 65,
            castTime: 1,
            cooldown: 60,
            duration: 0,
            description: "AOE fear, forcefully sending enemies running",
            isAOE: true,
          },
        },
      },
    ],
  },
  22: {
    skills: [
      {
        id: 23,
        name: "Racial",
        skills: {},
      },
      {
        id: 24,
        name: "Horsemanship",
        skills: {
          "Summon Horse": {
            name: "Summon Horse",
            reqPoints: 20,
            mpCost: 22,
            castTime: 3,
            cooldown: 180,
            duration: 0,
            description: "Summon a horse",
          },
          "Horse Guardian": {
            name: "Horse Guardian",
            reqPoints: 31,
            mpCost: 5,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Take damage for your horse",
            basePower: 1,
          },
          "Horse Charge (Passive)": {
            name: "Horse Charge (Passive)",
            reqPoints: 40,
            mpCost: 0,
            castTime: 0,
            cooldown: 0,
            duration: 0,
            description: "Charge at target, dealing damage",
            isPassive: true,
          },
        },
      },
    ],
  },
};
